# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- v.0.2.0

pool:
  name:  'RHEL 9 Build Pool'
  demands:
  - agent.name -equals build-01-c


variables:
- name: 'artifactName'
  value: 'halt-web-portal'
- name: 'artifactRepoRootUrl'
  value: 'https://nexus.iiroc.ca/repository/rpm-stg-halt'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing dependencies..."
      npm install --force

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      set -e
      echo "Node version:"
      node -v
      echo "NPM version:"
      npm -v
      echo "Installing dependencies..."
      echo "Running build..."
      npm run build || { echo "Build failed!"; exit 1; }
      echo "Listing files after npm build"
      ls -l

      # if [ ! -d "./build" ]; then
      #   echo "React build folder not found!"
      #   exit 4
      # fi

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    options: "-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"
    goals: 'clean package'


- task: CopyFiles@2
  inputs:
    Contents: '**/noarch/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Bash@3
  inputs:
      targetType: 'inline'
      script: |        
        echo "Build artifacr staging : $BUILD_ARTIFACTSTAGINGDIRECTORY"
        echo "Agent build dir : $AGENT_BUILDDIRECTORY"
        echo "Copying to nexus..."

        NEW_VERSION_FULL_PATH=$(ls "$BUILD_ARTIFACTSTAGINGDIRECTORY"/target/rpm/halt-web-portal/RPMS/noarch/*.rpm)
        NEW_VERSION_FILE_NAME=$(ls "$BUILD_ARTIFACTSTAGINGDIRECTORY"/target/rpm/halt-web-portal/RPMS/noarch/)
        echo "Full path : $NEW_VERSION_FULL_PATH"
        echo "File name : $NEW_VERSION_FILE_NAME"

        VERSION=$(echo $NEW_VERSION_FILE_NAME | cut -d'-' -f4)
        echo "Version: $VERSION"
        
        RELEASE=$(echo $NEW_VERSION_FILE_NAME | cut -d'-' -f5)        
        RC_VERSION=$(echo $RELEASE | cut -d'.' -f1)
        echo "rc : $RC_VERSION"
      
        echo "Source file to copy : https://nexus.iiroc.ca/repository/rpm-stg-halt/v$VERSION/halt-web-portal/$NEW_VERSION_FILE_NAME"
        curl -v -k -u stg-dev:5tg-d3v --upload-file "$NEW_VERSION_FULL_PATH" "https://nexus.iiroc.ca/repository/rpm-stg-halt/v$VERSION/halt-web-portal/$NEW_VERSION_FILE_NAME"
        echo "Done deployment to nexus"